JiggysCarRental/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JiggysCarRental.Models;
using Microsoft.AspNetCore.Authorization;

namespace JiggysCarRental.Controllers
{
    [Authorize]
    public class RentalController : Controller
    {
        private readonly CarDbContext _context;

        public RentalController(CarDbContext context)
        {
            _context = context;
        }

        // GET: Rental
        [Authorize (Roles = "Employee")]
        public async Task<IActionResult> Index()
        {
              return _context.Rentals != null ? 
                          View(await _context.Rentals.ToListAsync()) :
                          Problem("Entity set 'CarDbContext.Rentals'  is null.");
        }

        // GET: Rental/Details/5
        [Authorize (Roles = "Employee")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Rentals == null)
            {
                return NotFound();
            }

            var rental = await _context.Rentals
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (rental == null)
            {
                return NotFound();
            }

            return View(rental);
        }

        // GET: Rental/Create
        public IActionResult Upsert(int id = 0)
        {
            if (id == 0)
                return View(new Rental());
            else
                return View(_context.Rentals.Find(id));
        }

        // POST: Rental/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert([Bind("TransactionId,VehicleName,RentCost,PickupDate,ReturnDate,GPSNavigation,InfantAndChildSeats")] Rental rental)
        {
            if (ModelState.IsValid)
            {
                if (rental.TransactionId == 0)
                {
                    _context.Add(rental);
                }
                else
                    _context.Update(rental);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rental);
        }

        // GET: Rental/Delete/5
        [Authorize (Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Rentals == null)
            {
                return NotFound();
            }

            var rental = await _context.Rentals
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (rental == null)
            {
                return NotFound();
            }

            return View(rental);
        }

        // POST: Rental/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize (Roles = "Employee")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Rentals == null)
            {
                return Problem("Entity set 'CarDbContext.Rentals'  is null.");
            }
            var rental = await _context.Rentals.FindAsync(id);
            if (rental != null)
            {
                _context.Rentals.Remove(rental);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RentalExists(int id)
        {
          return (_context.Rentals?.Any(e => e.TransactionId == id)).GetValueOrDefault();
        }
    }
}

JiggysCarRental/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JiggysCarRental.Models;
using JiggysCarRental.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;

namespace JiggysCarRental.Controllers
{
    public class VehicleController : Controller
    {
        private readonly CarDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VehicleController(CarDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Vehicle
        public async Task<IActionResult> Index()
        {
              return _context.Vehicles != null ? 
                          View(await _context.Vehicles.ToListAsync()) :
                          Problem("Entity set 'CarDbContext.Vehicles'  is null.");
        }

        // GET: Vehicle/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }
            RentalViewModel RentalViewModel = new()
            {
                Vehicle = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.Id == id),
                Rental = new Rental()
            };

            if (RentalViewModel.Vehicle == null)
            {
                return NotFound();
            }

            return View(RentalViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(int? id, RentalViewModel rentalViewModel)
        {
            RentalViewModel RentalViewModel = new()
            {
                Vehicle = await _context.Vehicles
                            .FirstOrDefaultAsync(m => m.Id == id),
                Rental = new Rental()
            };
            if (ModelState.IsValid)
            {
                Console.WriteLine("modelstate Valid");
                rentalViewModel.Rental.VehicleName = RentalViewModel.Vehicle.VehicleName;
                rentalViewModel.Rental.RentCost = RentalViewModel.Vehicle.RentCost;
                _context.Add(rentalViewModel.Rental);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home", null);
            }
            Console.WriteLine("modelstate InValid");
            return View(RentalViewModel);
        }


        // GET: Vehicle/Edit/5
        [Authorize (Roles = "Admin")]
        public IActionResult Upsert(int id = 0)
        {
            if (id == 0)
            {
                var vehicle = new Vehicle
                {
                    StartDateAvailable = DateTime.Now,
                    EndDateAvailable = (DateTime.Now).AddDays(30)
                };
                return View(vehicle);
            }
            else
                return View(_context.Vehicles.Find(id));
        }

        // POST: Vehicle/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize (Roles = "Admin")]
        public async Task<IActionResult> Upsert(int id,[Bind("Id,VehicleName,Image,Details,RentCost,NumberOfPassengers,NumberOLargeBags,UsbAdapter,ReverseCamera,PushStart,Bluetooth,ToolsControl,SteeringControl,ThermalControl,HeatedSeat,AutomaticTransmission,FourWheelDrive,LeatherSeats,Aux,StartDateAvailable,EndDateAvailable")] Vehicle vehicle)
        {

            if (ModelState.IsValid)
            {
                Console.WriteLine("Modelstate Valid");
                var files = HttpContext.Request.Form.Files;
                string webroot = _webHostEnvironment.WebRootPath;
                string uploadpath = webroot + AppConst.UploadPath;
                if (!Directory.Exists(uploadpath))
                {
                    Directory.CreateDirectory(uploadpath);
                }
                string fileName = Guid.NewGuid().ToString();
                string ext = Path.GetExtension(files[0].FileName);
                using (var fs = new FileStream(Path.Combine(uploadpath, fileName + ext), FileMode.Create))
                {
                    files[0].CopyTo(fs);
                }
                vehicle.Image = fileName + ext;
                if (vehicle.Id == 0)
                {
                    vehicle.StartDateAvailable = DateTime.Now;
                    _context.Add(vehicle);
                }
                else
                    _context.Update(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            Console.WriteLine("Modelstate Invalid");
            return View(vehicle);
        }

        // GET: Vehicle/Delete/5
        [Authorize (Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehicles == null)
            {
                return Problem("Entity set 'CarDbContext.Vehicles'  is null.");
            }
            var vehicle = await _context.Vehicles.FindAsync(id);
            if (vehicle != null)
            {
                _context.Vehicles.Remove(vehicle);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
          return (_context.Vehicles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

JiggysCarRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JiggysCarRental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JiggysCarRental.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<style>
    .logo{
        font-weight: bold;
        line-height: normal;
        margin: 0 2rem;
    }
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-center logo text-success" asp-area="" asp-controller="Home" asp-action="Index">JIGGY'S CAR <br /> RENTAL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
        <main role="main">
            @RenderBody()
        </main>
        <footer class="py3 my-4">
            <div>
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                    </li>
                    @if(User.IsInRole("Employee"))
                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Rental" asp-action="Index">BOOKINGS</a>
                    </li>
                    }
                    @if(User.IsInRole("Admin"))
                    {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Vehicle" asp-action="Index">VEHICLES</a>
                    </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">PRIVACY</a>
                    </li>
                </ul>
            </div>
                <div class="container d-flex justify-content-center">
                    All right reserved | &copy; 2023 - JiggysCarRental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
        </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>